apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostblog-pvc
  namespace: ghostblog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
